use api_nectara;
INSERT INTO butterflies (id, common_name, scientific_name, location, description, habitat, image, migratory)
VALUES
("1","Mariposa Reina Africana","Danaus chrysippus","África subsahariana","Color naranja intenso con alas negras y puntos blancos. Muy común en todo el continente.","Sabana y zonas abiertas","https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Danaus_chrysippus_Female_by_kadavoor.jpg/1280px-Danaus_chrysippus_Female_by_kadavoor.jpg", TRUE),
("2","Mariposa Zuleika","Amauris zuleika","África oriental","Imita a la Reina Africana como estrategia de defensa. Vuela lentamente cerca de arbustos","Bosques húmedos y claros","https://static.inaturalist.org/photos/32533266/large.jpeg", FALSE),
("3","Mariposa Cola de Golondrina Verde","Papilio nireus","África occidental","Color negro con franjas verdes. Tiene colas similares a las de una golondrina.","Bosques y jardines","https://img.freepik.com/fotos-premium/deslumbrante-mariposa-cola-golondrina-esmeralda-descansa-alas-abiertas-hojas-hierba_501731-9148.jpg", FALSE),
("4","Mariposa Mocker","Hypolimnas misippus","África, Asia y Australia","Imita a mariposas tóxicas como defensa. Hembras presentan gran variación de colores.","Áreas abiertas y rurales","https://i.pinimg.com/736x/96/ee/ed/96eeed3c4a50580810e8258e04228143.jpg", TRUE),
("5","Mariposa Diadema","Hypolimnas salmacis","África tropical","Machos azul metálico con alas negras. Muy territorial.","Bosques y márgenes","https://i.pinimg.com/originals/3b/0c/de/3b0cde616b2bb8b819f846af0ae85d87.jpg", FALSE),
("6","Mariposa Falcón Africana","Euphaedra phaethusa","África occidental y central","Alas de color verde brillante con manchas negras. Habita en selvas húmedas.","Selvas tropicales","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Malachite_%28Siproeta_stelenes%29_dorsal_%281%29.jpg/500px-Malachite_%28Siproeta_stelenes%29_dorsal_%281%29.jpg", FALSE),
("7","Mariposa Espejo Africana","Acraea encedon","África tropical","Colores anaranjados con negro, imita a especies tóxicas para evitar depredadores.","Zonas abiertas y cálidas","https://media.istockphoto.com/id/116566192/es/foto/mariposa-monarca-danaus-plexippus.jpg?s=170667a&w=0&k=20&c=Yz1hKIK93dWAOGqeWtyKvvi-ZGXGpWQUFwROxtFLH14=", FALSE),
("8","Mariposa Pantera","Junonia terea","África subsahariana","Tiene manchas oculares llamativas en sus alas para ahuyentar depredadores.","Sabanas y praderas","https://w0.peakpx.com/wallpaper/222/717/HD-wallpaper-mariposa-ojos-en-las-alas-exelente-foto-delicada-exelente-foto-mariposa-delicada-ojos-en-las-alas.jpg", TRUE),
("9","Mariposa Pavo Real Africana","Precis octavia","África oriental y meridional","Muestra variaciones de color según la estación. Azul metálico en verano.","Campos y zonas rocosas","https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Gaudy_Commodore_winter_form.JPG/500px-Gaudy_Commodore_winter_form.JPG", TRUE),
("10","Mariposa Charaxes Jasius Africana","Charaxes jasius","África norte y mediterránea","Una de las mariposas más grandes de África. Alas anaranjadas con bordes negros.","Bosques mediterráneos","https://res.cloudinary.com/dauzwfc8z/image/upload/v1753869972/mariposas-africa/pzen8gfnv8szfd7jqww6.webp", FALSE),
("11","Mariposa de Cristal Africana","Cymothoe sangaris","Congo, Gabón, Camerún","Roja intensa y translúcida. Habita selvas densas del África central.","Selvas húmedas y profundas","https://s3.animalia.bio/animals/photos/full/original/greta-oto-glasswing-butterfly-6917391571.webp", FALSE),
("12","Mariposa Tigre Africana","Danaus petilia","África sur y oriental","Muy parecida a la Reina Africana, pero con alas más pálidas. Polinizadora de diversas plantas.","Praderas floridas","https://static.inaturalist.org/photos/215552029/large.jpg", TRUE),
("13","Mariposa Azul del Cabo","Lepidochrysops bacchus","Sudáfrica","Pequeña mariposa azul con patrones oscuros. Endémica de áreas montañosas.","Zonas montañosas","https://www.junglexperiences.com/wp-content/uploads/2024/05/Conservacion-de-las-Mariposas-Azules.png", FALSE),
("14","Mariposa Monarca Africana","Danaus dorippus","África oriental","Subespecie africana de la Monarca. Carece de venas negras gruesas en las alas.","Praderas y campos abiertos","https://cumbrepuebloscop20.org/wp-content/uploads/2023/06/colorful-nature-orange-monarch-butterfly-with-floral-background.jpg", TRUE),
("15","Mariposa Árabe Africana","Colotis evagore","Norte de África y península arábiga","Pequeña mariposa blanca con toques rosados. Habita zonas áridas.","Zonas desérticas","https://wallpapers.com/images/hd/white-butterfly-2216-x-1477-w641n8nekx3slnpl.jpg", FALSE),
("16","Mariposa Aceitera Africana","Bicyclus anynana","África central y sur","Con manchas oculares marrón claro. Se adapta a diferentes estaciones.","Áreas húmedas con hierba alta","https://upload.wikimedia.org/wikipedia/commons/9/93/Lasiommata_megera_LC0066.jpg", FALSE),
("17","Mariposa Rayada del Bosque","Bebearia tentyris","Bosques tropicales del oeste africano","Marrón con rayas negras y bordes naranjas. Vuela bajo en áreas húmedas.","Bosques lluviosos","https://upload.wikimedia.org/wikipedia/commons/5/57/Dryadula-phaetusa-butterfly.jpg", FALSE),
("18","Mariposa Naranja del Desierto","Colotis amata","África del Norte y zonas semiáridas","Color naranja intenso. Se alimenta de flores resistentes a la sequía.","Zonas semiáridas","https://pictureinsect.com/wiki-image/1080/153938942259888133.jpeg", TRUE),
("19","Mariposa Bosque de Marfil","Euphaedra medon","Costa de Marfil, Ghana","Colores brillantes, muy activa durante el día en bosques lluviosos.","Bosques frondosos","https://images.unsplash.com/photo-1605999360145-079adb1cf613?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Ym9zcXVlJTIwbGx1dmlvc28lMjBkZSUyMG1hcmlwb3Nhc3xlbnwwfHwwfHx8MA%3D%3D", FALSE);